name: Update Badges

on:
  push:
    branches: [ main ]
  schedule:
    # Update badges daily at 2 AM UTC
    - cron: '0 2 * * *'

permissions:
  contents: read
  actions: read

jobs:
  update-badges:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python 3.12
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install coverage pytest

    - name: Run coverage for badge
      run: |
        python -m pytest tests/test_flight_simulator_core.py tests/test_flight_mechanics.py \
          --cov=core.flight_simulator \
          --cov-report=term-missing || true

        # Extract coverage percentage for flight simulator
        COVERAGE=$(python -m coverage report --include="core/flight_simulator.py" | grep "TOTAL" | awk '{print $4}' | sed 's/%//')
        echo "FLIGHT_SIMULATOR_COVERAGE=${COVERAGE}" >> $GITHUB_ENV

    - name: Create badge data
      run: |
        echo "Flight Simulator Coverage: ${FLIGHT_SIMULATOR_COVERAGE}%"

        # Determine badge color
        if (( $(echo "${FLIGHT_SIMULATOR_COVERAGE} >= 90" | bc -l) )); then
          BADGE_COLOR="brightgreen"
        elif (( $(echo "${FLIGHT_SIMULATOR_COVERAGE} >= 80" | bc -l) )); then
          BADGE_COLOR="green"
        elif (( $(echo "${FLIGHT_SIMULATOR_COVERAGE} >= 70" | bc -l) )); then
          BADGE_COLOR="yellow"
        else
          BADGE_COLOR="red"
        fi

        echo "BADGE_COLOR=${BADGE_COLOR}" >> $GITHUB_ENV

    - name: Update README badges
      run: |
        # This would update README.md with current coverage badges
        echo "Coverage badge would be: https://img.shields.io/badge/Flight%20Simulator%20Coverage-${FLIGHT_SIMULATOR_COVERAGE}%25-${BADGE_COLOR}"